#!/bin/bash
TAG=$1

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker tag "$IMAGE_NAME" "${IMAGE_NAME}:develop"
docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TAG}-develop"

docker push "${IMAGE_NAME}:develop" && docker push "${IMAGE_NAME}:${TAG}-develop"