#!/bin/bash
VERSION=$1

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${VERSION}"

docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${VERSION}"